---

# The project Docker compose file for development.

version: '2'

services:

  db:
    image: camptocamp/getitfixed-postgresql:latest
    restart: unless-stopped

  test:
    image: ${DOCKER_BASE}-build:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ${PWD}/getitfixed:/app/getitfixed
      - ${PWD}/acceptance_tests:/app/acceptance_tests
    environment:
      - PGHOST=db
      - PGHOST_SLAVE=db
      - PGPORT=5432
      - PGUSER=getitfixed
      - PGPASSWORD=getitfixed
      - PGDATABASE=getitfixed
      - INI_FILE=tests.ini
    command: 'pytest /app/acceptance_tests'
