---

# The project Docker compose file for development.

version: '2'

services:

  db:
     image: camptocamp/getitfixed-postgresql:latest

  getitfixed:
    image: ${DOCKER_BASE}-getitfixed:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGOPTIONS
      - GUNICORN_PARAMS
      - VISIBLE_WEB_PROTOCOL
      - VISIBLE_WEB_HOST
      - VISIBLE_ENTRY_POINT
      - PRINT_URL
      - C2CWSGIUTILS_CONFIG
      - SMTP_USER
      - SMTP_PASSWORD
      - PROXY_PREFIX
    ports:
      - ${DOCKER_PORT}:8080
