---

# The project Docker compose file for development.

version: '2'

volumes:
  smtp_maildir:

services:

  db:
    image: camptocamp/getitfixed-postgresql:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=getitfixed
      - POSTGRES_PASSWORD=getitfixed
      - POSTGRES_DB=getitfixed

  redis:
    image: redis:5
    restart: unless-stopped

  getitfixed:
    image: ${DOCKER_BASE}-getitfixed:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGOPTIONS
      - INI_FILE
      - PROXY_PREFIX
    command: 'pserve getitfixed://${INI_FILE}'
    ports:
      - ${DOCKER_PORT}:8080

  smtp:
    image: camptocamp/smtp-sink:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/

  courier-imap:
    image: camptocamp/courier-imap:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/

  webmail:
    image: camptocamp/sqwebmail:latest
    environment:
      - IMAP_HOSTNAME=courier-imap
      - SMTP_HOSTNAME=smtp-sink
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    ports:
      - 8082:80

  db_tests:
    image: camptocamp/getitfixed-postgresql:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=getitfixed
      - POSTGRES_PASSWORD=getitfixed
      - POSTGRES_DB=getitfixed_tests

  test:
    image: ${DOCKER_BASE}-build:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    depends_on:
      - db_tests
    volumes:
      - ${PWD}/getitfixed:/app/getitfixed
      - ${PWD}/acceptance_tests:/app/acceptance_tests
    environment:
      - PGHOST=db_tests
      - PGHOST_SLAVE=db_tests
      - PGPORT=5432
      - PGUSER=getitfixed
      - PGPASSWORD=getitfixed
      - PGDATABASE=getitfixed_tests
      - INI_FILE=tests.ini
    command: 'pytest -vv /app/acceptance_tests'
