---

# The project Docker compose file for development.

version: '2'

services:

  getitfixed:
    image: ${DOCKER_BASE}-build:${DOCKER_TAG}
    volumes:
      - ${PWD}/getitfixed:/app/getitfixed
      - ${PWD}/acceptance_tests:/app/acceptance_tests
      - ${PWD}/../c2cgeoform/c2cgeoform:/usr/local/lib/python3.8/site-packages/c2cgeoform
    command: pserve --reload getitfixed://development.ini
