#!/bin/bash -e

function usage(){
    printf "\n"
    printf "Usage: $0 [-h] [--test]\n"
    printf "\n"
    printf "Options:\n"
    printf "  -h       Show this help message\n"
    printf "  --test   Test deployment on testpypi\n"
}

TEST=false

while [ -n "$1" ]; do # while loop starts
    case "$1" in
    -h) usage; exit 0 ;; # Show help
    --test) TEST=true ;; # This is a deploy test
    *) echo "Option $1 not recognized" ;;
    esac
    shift
done

if [[ "${GITHUB_ACTIONS}" == "true" ]]
then
    if [[ "${GITHUB_REF}" =~ ^refs/tags/.* ]]
    then
      GIT_TAGS=$(echo "${GITHUB_REF}"|sed 's|^refs/tags/||g')
    elif [[ "${GITHUB_REF}" =~ ^refs/heads/.* ]]
    then
      GIT_BRANCH=$(echo "${GITHUB_REF}"|sed 's|^refs/heads/||g')
    fi
else
    GIT_BRANCH=`git rev-parse --abbrev-ref HEAD`
    GIT_TAGS=`git tag --points-at HEAD`
fi

make docker-compile-catalog

function deploy_pypi {
    VERSION=$1 python3 setup.py egg_info sdist bdist_wheel
    twine upload dist/*
}

if [ $TEST = true ] ; then
    python3 setup.py egg_info sdist bdist_wheel
    twine upload -r testpypi dist/*
else
    # Deploy tags
    for GIT_TAG in ${GIT_TAGS}
    do
        deploy_pypi $GIT_TAG
    done
fi
