#!/bin/bash -ex

make docker-compile-catalog

# Prepare .pypirc config
echo "[distutils]" > ~/.pypirc
echo "index-servers = pypi" >> ~/.pypirc
echo "[pypi]" >> ~/.pypirc
echo "repository:https://upload.pypi.org/legacy/" >> ~/.pypirc
echo "username:arnaud-morvan" >> ~/.pypirc
echo "password:${PYPI_PASSWORD}" >> ~/.pypirc

# Deploy pypi build
if [ "${TRAVIS_EVENT_TYPE}" = cron ]
then
    python setup.py egg_info --tag-date --tag-build=dev sdist bdist_wheel upload -r pypi
elif [ "${TRAVIS_TAG}" != "" ]
then
    VERSION=${TRAVIS_TAG} python setup.py egg_info sdist bdist_wheel upload -r pypi
else
    python setup.py egg_info sdist bdist_wheel upload -r pypi
fi
