"""First revision

Revision ID: 43b1bfa631fd
Revises: 
Create Date: 2019-08-01 15:55:24.440354

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '43b1bfa631fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.Text(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, management=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue')),
    sa.UniqueConstraint('hash', name=op.f('uq_issue_hash')),
    schema='getitfixed'
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['getitfixed.issue.id'], name=op.f('fk_photo_issue_id_issue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo')),
    schema='getitfixed'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo', schema='getitfixed')
    op.drop_table('issue', schema='getitfixed')
    # ### end Alembic commands ###
