---

name: Continuous integration

on:
  push:

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TX_USR: ${{ secrets.TX_USR }}
      TX_PWD: ${{ secrets.TX_PWD }}
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Lint
        run: make check
      - name: Tests
        run: make test
      - name: Docker compose logs
        if: ${{ always() }}
        run: |
          docker-compose logs
          docker-compose down -v --remove-orphans

      # Publish
      - run: sudo python3 -m pip install twine wheel
      - name: Test deploy pypi
        if: >
          github.repository == 'camptocamp/getitfixed'
          && !startsWith(github.ref, 'refs/tags/')
        run: scripts/deploy-pypi --test
      - name: Deploy PyPI
        if: >
          github.repository == 'camptocamp/getitfixed'
          && success()
          && (
            startsWith(github.ref, 'refs/tags/')
          )
        run: scripts/deploy-pypi
