---

name: Continuous integration

on:
  push:

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    permissions:
      id-token: write
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Lint
        run: make check
      - name: Tests
        run: make test
      - name: Docker compose logs
        if: ${{ always() }}
        run: |
          docker compose logs
          docker compose down -v --remove-orphans
      - name: Build for PyPI
        if: >
          github.repository == 'camptocamp/getitfixed'
          && success()
          && startsWith(github.ref, 'refs/tags/')
        run: |
          python3 -m pip install setuptools wheel
          scripts/build-pypi
      - name: Publish to PyPI
        if: >
          github.repository == 'camptocamp/getitfixed'
          && success()
          && startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
